In [1]:
import torch
from pyqcu.ascend import qcu
from pyqcu.ascend.io import *
from pyqcu.ascend.define import *
from pyqcu.ascend.dslash import *
from pyqcu.ascend.inverse import *
device = torch.device('cpu')
file_name = 'test.ascend-dev56'
_qcu = qcu(lat_size=[16, 16, 16, 16], dtype=torch.complex128, device=device)
_qcu.load(file_name=file_name)
_qcu.init()
# _ = _qcu.solve()
# _qcu.save(file_name=file_name)

self.lat_size: [16, 16, 16, 16]
self.grid_size: [1, 1, 1, 1]
self.grid_index: [0, 0, 0, 0]
self.local_lat_size: [16, 16, 16, 16]
Using device: cpu
@My Rank:0/1, Local Rank:0@

Grid Index T: 0, Z: 0, Y: 0, X: 0
Grid Lat T: 16, Z: 16, Y: 16, X: 16
All Dest Shape: (4, 3, 16, 16, 16, 16)
Dest Shape: (4, 3, 16, 16, 16, 16)
Grid Index T: 0, Z: 0, Y: 0, X: 0
Grid Lat T: 16, Z: 16, Y: 16, X: 16
All Dest Shape: (4, 3, 16, 16, 16, 16)
Dest Shape: (4, 3, 16, 16, 16, 16)
Grid Index T: 0, Z: 0, Y: 0, X: 0
Grid Lat T: 16, Z: 16, Y: 16, X: 16
All Dest Shape: (3, 3, 4, 16, 16, 16, 16)
Dest Shape: (3, 3, 4, 16, 16, 16, 16)
Grid Index T: 0, Z: 0, Y: 0, X: 0
Grid Lat T: 16, Z: 16, Y: 16, X: 16
All Dest Shape: (4, 3, 4, 3, 16, 16, 16, 16)
Dest Shape: (4, 3, 4, 3, 16, 16, 16, 16)
self.dof_list:[12, 24, 24, 24, 24]
Building grid list:
  Level 0: 16x16x16x16
  Level 1: 8x8x8x8
  Level 2: 4x4x4x4
  Level 3: 2x2x2x2
self.grid_list:[[16, 16, 16, 16], [8, 8, 8, 8], [4, 4, 4, 4], [2, 2, 2, 2]]


In [2]:
_qcu.matvec(_qcu.x)-_qcu.b

tensor([[[[[[ 9.0335e-02+3.1315e-02j,  4.6233e-01-2.3562e-03j,
              3.9166e-01+2.2245e-01j,  ...,
              4.6719e-01+2.0049e-01j,  3.0271e-02+1.6073e-01j,
              9.1981e-03-8.4720e-02j],
            [ 9.3395e-02+1.9551e-01j,  6.1416e-02-2.1687e-01j,
              1.6008e-01+4.8770e-01j,  ...,
              1.9626e-01+2.1631e-01j, -4.9455e-02-1.9107e-01j,
              2.1588e-01-1.6327e-01j],
            [ 4.0633e-01+2.9066e-01j,  3.8953e-01+8.5440e-02j,
             -1.0851e-02+1.3503e-01j,  ...,
              4.7990e-01+1.2228e-01j,  1.2563e-01+1.4860e-01j,
              4.6457e-01+1.7774e-01j],
            ...,
            [ 8.5045e-02-9.5474e-03j, -9.5330e-02+6.9947e-02j,
              4.0730e-01+2.2135e-02j,  ...,
              1.6184e-03+2.2525e-01j, -1.7626e-01+3.5811e-01j,
             -6.1803e-02+5.0749e-02j],
            [ 2.0143e-01+3.7969e-01j,  2.1187e-01+2.2376e-01j,
              4.8441e-01+2.9749e-01j,  ...,
              4.5049e-02+2.9093e-01j, -1

In [3]:
_x = hdf5_xxx2xxx(device=device, file_name=file_name+'-x.h5')
_b = hdf5_xxx2xxx(device=device, file_name=file_name+'-b.h5')
_U = hdf5_xxx2xxx(device=device, file_name=file_name+'-U.h5')
_clover_term = hdf5_xxx2xxx(
    device=device, file_name=file_name+'-clover_term.h5')

Dest Shape: (4, 3, 16, 16, 16, 16)
Dest Shape: (4, 3, 16, 16, 16, 16)
Dest Shape: (3, 3, 4, 16, 16, 16, 16)
Dest Shape: (4, 3, 4, 3, 16, 16, 16, 16)


In [4]:
_x-_qcu.x

tensor([[[[[[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            ...,
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

           [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            ...,
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

           [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
          

In [5]:
_b-_qcu.b

tensor([[[[[[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            ...,
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

           [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            ...,
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

           [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
          

In [6]:
_U-_qcu.U

tensor([[[[[[[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             ...,
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

            [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             ...,
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

            [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+

In [7]:
_clover_term-_qcu.clover_term

tensor([[[[[[[[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              ...,
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

             [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              ...,
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

             [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+

In [8]:
_clover_term

tensor([[[[[[[[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              ...,
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

             [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              ...,
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

             [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+