In [1]:
from pyqcu.ascend.io import *

In [2]:
U=hdf5_xxx2xxx(file_name='U.h5')

Dest Shape: (3, 3, 4, 2, 2, 2, 2)


In [3]:
U

tensor([[[[[[[0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j]],

            [[1.+0.j, 1.+0.j],
             [1.+0.j, 1.+0.j]]],


           [[[2.+0.j, 2.+0.j],
             [2.+0.j, 2.+0.j]],

            [[3.+0.j, 3.+0.j],
             [3.+0.j, 3.+0.j]]]],



          [[[[0.+1.j, 0.+1.j],
             [0.+1.j, 0.+1.j]],

            [[1.+1.j, 1.+1.j],
             [1.+1.j, 1.+1.j]]],


           [[[2.+1.j, 2.+1.j],
             [2.+1.j, 2.+1.j]],

            [[3.+1.j, 3.+1.j],
             [3.+1.j, 3.+1.j]]]],



          [[[[0.+2.j, 0.+2.j],
             [0.+2.j, 0.+2.j]],

            [[1.+2.j, 1.+2.j],
             [1.+2.j, 1.+2.j]]],


           [[[2.+2.j, 2.+2.j],
             [2.+2.j, 2.+2.j]],

            [[3.+2.j, 3.+2.j],
             [3.+2.j, 3.+2.j]]]],



          [[[[0.+3.j, 0.+3.j],
             [0.+3.j, 0.+3.j]],

            [[1.+3.j, 1.+3.j],
             [1.+3.j, 1.+3.j]]],


           [[[2.+3.j, 2.+3.j],
             [2.+3.j, 2.+3.j]],

            [[3.+3.j

In [4]:
import torch
from pyqcu.ascend.define import slice_dim
x, y, z, t = 2, 3, 4, 5
a = torch.arange(x*y*z*t).reshape(t, z, y, x)
print(a)
ward=1
a[slice_dim(ward=ward,point=0)]

tensor([[[[  0,   1],
          [  2,   3],
          [  4,   5]],

         [[  6,   7],
          [  8,   9],
          [ 10,  11]],

         [[ 12,  13],
          [ 14,  15],
          [ 16,  17]],

         [[ 18,  19],
          [ 20,  21],
          [ 22,  23]]],


        [[[ 24,  25],
          [ 26,  27],
          [ 28,  29]],

         [[ 30,  31],
          [ 32,  33],
          [ 34,  35]],

         [[ 36,  37],
          [ 38,  39],
          [ 40,  41]],

         [[ 42,  43],
          [ 44,  45],
          [ 46,  47]]],


        [[[ 48,  49],
          [ 50,  51],
          [ 52,  53]],

         [[ 54,  55],
          [ 56,  57],
          [ 58,  59]],

         [[ 60,  61],
          [ 62,  63],
          [ 64,  65]],

         [[ 66,  67],
          [ 68,  69],
          [ 70,  71]]],


        [[[ 72,  73],
          [ 74,  75],
          [ 76,  77]],

         [[ 78,  79],
          [ 80,  81],
          [ 82,  83]],

         [[ 84,  85],
          [ 86,  87]

tensor([[[  0,   1],
         [  2,   3],
         [  4,   5]],

        [[ 24,  25],
         [ 26,  27],
         [ 28,  29]],

        [[ 48,  49],
         [ 50,  51],
         [ 52,  53]],

        [[ 72,  73],
         [ 74,  75],
         [ 76,  77]],

        [[ 96,  97],
         [ 98,  99],
         [100, 101]]])