In [20]:
import pyqcu

In [21]:
import h5py
import numpy as np
import cupy as cp
import mpi4py.MPI as MPI
comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

In [22]:
size

1

In [23]:
a=cp.array([range(3**2)]).reshape(3,3)
b=cp.array([range(3**1)]).reshape(1,3)


In [24]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
b

array([[0, 1, 2]])

In [30]:
a*b

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16]])