In [1]:
import torch
from pyqcu.ascend import dslash
from pyqcu.ascend.include import *
# latt_size = (32, 32, 32, 32)
# latt_size = (32, 32, 16, 16)
# latt_size = (16, 16, 16, 32)
latt_size = (16, 16, 16, 16)
# latt_size = (32, 32, 32, 32)
# latt_size = (32, 32, 32, 64)
# latt_size = (4, 8, 8, 8)
# latt_size = (8, 8, 8, 4)
# latt_size = (16, 8, 8, 8)
# latt_size = (8, 8, 8, 16)
# latt_size = (8, 8, 8, 8)
# latt_size = (4, 4, 4, 4)
# latt_size = (2, 2, 2, 2)
# mass = -3.5
# mass = -0.8
# mass = -0.5
mass = 0.05
mass = 0.0
mass = -0.05
# kappa = 0.4
# kappa = 0.125
# kappa = 0.5
kappa = 1 / (2 * mass + 8)
dtype = torch.complex128
# dtype = torch.complex64
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")
# Initialize lattice gauge theory
wilson = dslash.wilson_mg(
    latt_size=latt_size,
    kappa=kappa,
    dtype=dtype,
    device=device,
    verbose=False
)
clover = dslash.clover(
    latt_size=latt_size,
    kappa=kappa,
    dtype=dtype,
    device=device,
    verbose=False
)
U = wilson.generate_gauge_field(sigma=0.1, seed=42)

wilson.check_su3(U)
clover_term = clover.make_clover(U=U)

b = torch.randn(4, 3, latt_size[3], latt_size[2], latt_size[1], latt_size[0],
                dtype=dtype, device=device)
verbose = True


    @@@@@@######QCU NOTES START######@@@@@@@
    Guide:
    0. Required: MPI(e.g. 4.1.2), CUDA(e.g. 12.4), CMAKE(e.g. 3.22.1), GCC(e.g. 11.4.0), HDF5-MPI(e.g. 1.10.7,'apt install libhdf5-mpi-dev && export HDF5_MPI="ON" && pip install --no-binary=h5py h5py').
    1. The libqcu.so was compiled when pyqcu setup in download_path/PyQCU/lib, please add this path to your LD_LIBRARY_PATH.
    2. The QCU(PyQCU) splite grid by x->y->z->t, lattice by x->y->z->t->p->d[x,y,z,t]->c->c or x->y->z->t->c->s(->p) and x->y->z->t->c->s->c->s(->p).
    3. The QUDA(PyQUDA) splite grid by t->z->y->x, lattice by c->c->x->y->z->t->p->d[x,y,z,t] or c->s->x->y->z->t(->p) and c->s->c->s->x->y->z->t(->p).
    4. The QCU input params in numpy array(dtype=np.int32), argv in  numpy array(dtype=np.float32 or float64) array, set_ptrs in numpy array(dtype=np.int64), other in cupy array(dtype=cp.complex64 or complex128).
    5. The smallest lattice size is (wilson:x=4,y=4,z=4,t=4;clover:x=8,y=8,z=8,t=8) that QCU support

In [2]:
hopping_plus_list = []
hopping_minus_list = []
for ward in range(4):
    hopping_plus_list.append(wilson.give_hopping_plus(ward=ward, U=U))
    hopping_minus_list.append(wilson.give_hopping_minus(ward=ward, U=U))
Ab = wilson.give_wilson(src=b, U=U, with_I=False)
_Ab = torch.zeros_like(b)
for ward in range(4):
    _Ab += wilson.give_wilson_plus(ward=ward, src=b.reshape(
        [12]+list(U.shape[-4:])), hopping=hopping_plus_list[ward]).reshape([4, 3]+list(U.shape[-4:]))
    _Ab += wilson.give_wilson_minus(ward=ward, src=b.reshape(
        [12]+list(U.shape[-4:])), hopping=hopping_minus_list[ward]).reshape([4, 3]+list(U.shape[-4:]))
print(torch.norm(Ab-_Ab).item()/torch.norm(Ab).item())

2.1730434272736335e-16


In [ ]:
from pyqcu.ascend import inverse
mg = inverse.mg(b=b, wilson=wilson, U=U,
                clover=clover, clover_term=clover.add_I(clover_term=clover_term), verbose=verbose, max_iter=200,max_levels=5)

self.dof_list:[12, 24, 12, 8, 8, 8, 4, 12, 12, 12, 8, 4, 2, 4, 4, 24, 12, 12, 12, 4, 4, 4, 4, 4]
Building grid list:
  Level 0: 16x16x16x16
  Level 1: 8x8x8x8
  Level 2: 4x4x4x4
  Level 3: 2x2x2x2
self.grid_list:[[16, 16, 16, 16], [8, 8, 8, 8], [4, 4, 4, 4], [2, 2, 2, 2]]
Norm of b:1.1214332175006505
Norm of r:1.1214332175006505
Norm of x0:0.0
BICGSTAB-Iteration 0: Residual = 1.934631e-01, Time = 0.049927 s
BICGSTAB-Iteration 1: Residual = 6.392724e-02, Time = 0.049384 s
BICGSTAB-Iteration 2: Residual = 1.270226e-01, Time = 0.049161 s
BICGSTAB-Iteration 3: Residual = 2.154721e-02, Time = 0.049406 s
BICGSTAB-Iteration 4: Residual = 1.727070e-02, Time = 0.049714 s
BICGSTAB-Iteration 5: Residual = 9.424864e-03, Time = 0.049262 s
BICGSTAB-Iteration 6: Residual = 6.467579e-03, Time = 0.051019 s
BICGSTAB-Iteration 7: Residual = 9.468099e-03, Time = 0.050801 s
BICGSTAB-Iteration 8: Residual = 8.059373e-03, Time = 0.049656 s
BICGSTAB-Iteration 9: Residual = 6.475501e-03, Time = 0.051363 s
BICG

In [4]:
def matvec(src: torch.Tensor, U: torch.Tensor = U, clover_term: torch.Tensor = clover_term) -> torch.Tensor:
    return wilson.give_wilson(src, U)+clover.give_clover(clover_term=clover_term, src=src)


def _matvec(src: torch.Tensor) -> torch.Tensor:
    return mg.op_list[0].matvec(src=src)

In [5]:
%%time
%time Ab = matvec(b)
%time _Ab = _matvec(b)
print(torch.norm(U).item())
print(torch.norm(clover_term).item())
print(torch.norm(Ab).item())
print(torch.norm(_Ab).item())
print(torch.norm(Ab-_Ab).item()/torch.norm(_Ab).item())

CPU times: user 0 ns, sys: 2.78 ms, total: 2.78 ms
Wall time: 2.53 ms
CPU times: user 0 ns, sys: 1.81 ms, total: 1.81 ms
Wall time: 1.69 ms
886.8100134752651
42.62161161814855
995.3212618518644
995.3212618518644
1.7423617533260315e-16
CPU times: user 233 ms, sys: 9.55 ms, total: 243 ms
Wall time: 241 ms


In [6]:
import torch
c = torch.tensor([[ 1, 2, 3], [-1, 1, 4]] , dtype=torch.float)
c.shape

torch.Size([2, 3])

In [7]:
%time Ab = matvec(b)
%time _Ab = _matvec(b)

CPU times: user 2.83 ms, sys: 77 μs, total: 2.9 ms
Wall time: 2.69 ms
CPU times: user 3.71 ms, sys: 0 ns, total: 3.71 ms
Wall time: 3.69 ms


In [8]:
b0 = mg.b_list[0]
b1 = inverse.restrict(
    local_ortho_null_vecs=mg.lonv_list[0], fine_vec=b0)
_b0 = inverse.prolong(local_ortho_null_vecs=mg.lonv_list[0], coarse_vec=b1)
_b1 = inverse.restrict(
    local_ortho_null_vecs=mg.lonv_list[0], fine_vec=_b0)
print(_b1.flatten()[:100]/b1.flatten()[:100])

restrict:shape,coarse_dof:(torch.Size([24, 12, 8, 2, 8, 2, 8, 2, 8, 2]), 24)
EeTtZzYyXx,eTtZzYyXx->ETZYX
prolong:shape,fine_dof:(torch.Size([24, 12, 8, 2, 8, 2, 8, 2, 8, 2]), 12)
EeTtZzYyXx,ETZYX->eTtZzYyXx
restrict:shape,coarse_dof:(torch.Size([24, 12, 8, 2, 8, 2, 8, 2, 8, 2]), 24)
EeTtZzYyXx,eTtZzYyXx->ETZYX
tensor([1.0000+1.4941e-16j, 1.0000+4.8991e-16j, 1.0000+1.4701e-16j,
        1.0000-3.9880e-16j, 1.0000-1.3995e-15j, 1.0000-3.1207e-16j,
        1.0000-4.1317e-16j, 1.0000-4.5254e-18j, 1.0000+2.7993e-17j,
        1.0000+1.9542e-17j, 1.0000-4.4333e-16j, 1.0000+2.9816e-16j,
        1.0000-2.5956e-16j, 1.0000-1.7027e-16j, 1.0000+2.2483e-16j,
        1.0000+9.2456e-17j, 1.0000+9.1778e-17j, 1.0000-2.0375e-16j,
        1.0000+3.4848e-17j, 1.0000+9.2237e-18j, 1.0000+2.8985e-17j,
        1.0000+1.5992e-16j, 1.0000+1.3908e-16j, 1.0000-1.0939e-16j,
        1.0000+3.1413e-16j, 1.0000+3.0544e-17j, 1.0000+6.4484e-17j,
        1.0000-1.5074e-17j, 1.0000-1.4575e-16j, 1.0000-2.8884e-16j,
        

In [9]:
# _x = inverse.cg(b=b, matvec=matvec, verbose=verbose)
_x = inverse.bicgstab(b=b, matvec=_matvec, verbose=verbose)
# _x = inverse.bicgstab(b=b, matvec=mg.op_list[0].matvec, verbose=verbose)

Norm of b:887.1781621292079
Norm of r:1333.705314796359
Norm of x0:887.3932623463347
BICGSTAB-Iteration 0: Residual = 2.883550e+02, Time = 0.052143 s
BICGSTAB-Iteration 1: Residual = 1.313975e+02, Time = 0.051556 s
BICGSTAB-Iteration 2: Residual = 1.245560e+02, Time = 0.051971 s
BICGSTAB-Iteration 3: Residual = 8.471219e+01, Time = 0.052595 s
BICGSTAB-Iteration 4: Residual = 5.321982e+01, Time = 0.053393 s
BICGSTAB-Iteration 5: Residual = 5.124285e+01, Time = 0.052492 s
BICGSTAB-Iteration 6: Residual = 3.640808e+01, Time = 0.052292 s
BICGSTAB-Iteration 7: Residual = 3.012852e+01, Time = 0.052005 s
BICGSTAB-Iteration 8: Residual = 2.490964e+01, Time = 0.051943 s
BICGSTAB-Iteration 9: Residual = 1.055630e+02, Time = 0.051976 s
BICGSTAB-Iteration 10: Residual = 3.769020e+01, Time = 0.053444 s
BICGSTAB-Iteration 11: Residual = 3.302696e+01, Time = 0.051978 s
BICGSTAB-Iteration 12: Residual = 3.035887e+01, Time = 0.051910 s
BICGSTAB-Iteration 13: Residual = 2.970921e+01, Time = 0.051400 s
B

In [ ]:
x = mg.solve()
mg.plot()

Norm of b:887.1781621292079
Norm of r:1332.1983476554922
Norm of x0:885.7819051464064
restrict:shape,coarse_dof:(torch.Size([24, 12, 8, 2, 8, 2, 8, 2, 8, 2]), 24)
EeTtZzYyXx,eTtZzYyXx->ETZYX
Norm of b:153.97996783614417
Norm of r:153.97996783614417
Norm of x0:0.0
restrict:shape,coarse_dof:(torch.Size([12, 24, 4, 2, 4, 2, 4, 2, 4, 2]), 12)
EeTtZzYyXx,eTtZzYyXx->ETZYX
Norm of b:0.37777940950847
Norm of r:0.37777940950847
Norm of x0:0.0
restrict:shape,coarse_dof:(torch.Size([8, 12, 2, 2, 2, 2, 2, 2, 2, 2]), 8)
EeTtZzYyXx,eTtZzYyXx->ETZYX
Norm of b:4.358110728270434e-05
Norm of r:4.358110728270434e-05
Norm of x0:0.0
MG-3-BICGSTAB-Iteration 0: Residual = 7.330998e-09, Time = 0.003975 s
Converged at iteration 0 with residual 7.330998e-09

Performance Statistics:
Total iterations: 1
Total time: 0.004018 seconds
Average time per iteration: 0.003975 s
Final residual: 7.33e-09
prolong:shape,fine_dof:(torch.Size([8, 12, 2, 2, 2, 2, 2, 2, 2, 2]), 12)
EeTtZzYyXx,ETZYX->eTtZzYyXx
MG-2-BICGSTAB-Itera

In [ ]:
mg.lonv_list[0].shape

torch.Size([12, 12, 16, 2, 8, 2, 8, 2, 8, 2])

In [ ]:
(mg.b_list[0]-mg.op_list[0].matvec(x.reshape([12]+list(x.shape[-4:])))).flatten()[:100]

tensor([ 1.2258e-08+1.4085e-09j,  1.1137e-08+3.0767e-09j,
         1.0850e-08+2.7296e-09j,  1.1480e-08+2.3517e-09j,
         5.3358e-09-6.3870e-09j,  5.6234e-09-2.7190e-09j,
         1.7663e-09-9.7798e-09j,  1.3257e-09-7.9774e-09j,
        -2.7585e-09-1.0005e-08j, -3.2906e-09-1.0468e-08j,
        -2.6696e-09-9.2459e-09j, -9.2288e-10-6.8303e-09j,
        -1.8328e-09-6.8449e-09j,  2.7797e-09-1.3176e-09j,
         4.9427e-09-3.3441e-09j,  7.8677e-09+2.4890e-09j,
         1.2114e-08-2.8133e-10j,  1.6364e-08+2.2167e-09j,
         1.2841e-08+1.1828e-09j,  1.5584e-08-2.1704e-09j,
         1.0413e-08+1.3773e-09j,  9.8137e-09-9.7206e-09j,
         7.3698e-09-6.9877e-09j, -1.7723e-09-1.0143e-08j,
         3.1210e-09-1.0030e-08j,  9.0408e-11-9.3489e-09j,
        -1.1385e-09-7.2779e-09j, -2.4249e-10-8.6430e-09j,
        -2.8433e-12-2.3927e-09j,  2.4782e-09-5.1080e-09j,
         5.0934e-09-1.6023e-11j,  8.9606e-09+1.0612e-09j,
         1.3093e-08+4.2754e-09j,  1.1731e-08+7.7546e-10j,
         1.778

In [ ]:
print(torch.norm(x-_x).item()/torch.norm(_x).item())

1.0883627241862597e-07


In [ ]:
mg.num_levels

4

In [ ]:
index = -1
mg.u_list[-1] = inverse.bicgstab(b=torch.ones_like(mg.b_list[-1]),
                                 matvec=mg.op_list[-1].matvec, verbose=verbose,max_iter=10000)

Norm of b:19.595917942265423
Norm of r:1082.2805779702926
Norm of x0:19.299070488371154
BICGSTAB-Iteration 0: Residual = 2.159815e-01, Time = 0.006184 s
BICGSTAB-Iteration 1: Residual = 4.854043e-05, Time = 0.003940 s
BICGSTAB-Iteration 2: Residual = 1.475457e-08, Time = 0.003474 s
Converged at iteration 2 with residual 1.475457e-08

Performance Statistics:
Total iterations: 3
Total time: 0.013789 seconds
Average time per iteration: 0.004533 s
Final residual: 1.48e-08


In [ ]:
e=0

_src_c = torch.zeros_like(mg.b_list[-1])
_src_c[e][slice_dim(ward=0, start=0)] = 1.0
print(_src_c.shape)
print(_src_c[slice_dim(dim=5,ward=0+1, start=0)].shape)
print(torch.sum(_src_c))


torch.Size([12, 4, 2, 2, 2])
torch.Size([12, 2, 2, 2, 2])
tensor(16.+0.j, device='cuda:0', dtype=torch.complex128)


In [ ]:
list(slice_dim(ward=0, start=0))

[slice(0, None, 2),
 slice(None, None, None),
 slice(None, None, None),
 slice(None, None, None)]

In [ ]:
torch.sum(_src_c[e][0::2,:,:,:])

tensor(16.+0.j, device='cuda:0', dtype=torch.complex128)

In [ ]:
i=1
mg.op_list[i].hopping.M_minus_list[-4].flatten()[:100]-mg.op_list[i].hopping.M_minus_list[-1].flatten()[:100]

tensor([ 0.0200+1.9024e-04j, -0.1334+4.0048e-03j,  0.0389+2.2812e-03j,
         0.0327-1.4303e-03j, -0.1089+1.6411e-02j, -0.0035+1.5555e-03j,
        -0.0375+3.3496e-03j, -0.0151+3.5926e-03j, -0.0976+4.1068e-03j,
         0.0077+4.5784e-03j,  0.0162+1.3564e-02j, -0.0024+7.0265e-03j,
        -0.0086-5.2869e-03j, -0.0339+6.1866e-04j, -0.0454+2.7638e-03j,
        -0.0286+2.8571e-03j, -0.1086+1.5959e-03j, -0.0262+7.5431e-03j,
        -0.0032-8.1550e-04j, -0.1267-4.1071e-03j, -0.0216+5.2206e-03j,
        -0.0325+2.7229e-03j, -0.0382-7.7101e-04j, -0.0418-1.1397e-03j,
        -0.1080+1.3557e-03j, -0.0324+2.9463e-04j,  0.1156+1.4171e-02j,
        -0.1137-8.3098e-03j, -0.0343+4.7545e-03j, -0.0287+9.7801e-04j,
        -0.0146+2.9055e-03j,  0.1120-1.5553e-03j, -0.0149-2.6805e-03j,
         0.0939+1.4137e-02j,  0.1012+1.9951e-02j, -0.1124-8.0826e-03j,
        -0.0154+3.1630e-04j,  0.0013-2.3538e-03j,  0.0204-2.8005e-03j,
        -0.0059+8.5151e-03j, -0.0858-7.4037e-03j,  0.0160-1.1882e-02j,
      

In [ ]:
mg.op_list[i].hopping.M_minus_list[-2].flatten()[:100]

tensor([ 0.0494+6.3950e-03j, -0.0395-4.7894e-03j, -0.0492-5.6275e-03j,
        -0.0465-1.2881e-03j, -0.0357-5.9261e-04j, -0.0425-2.0141e-03j,
        -0.0612-7.9945e-04j, -0.0715+1.6224e-03j,  0.0497+5.8696e-03j,
        -0.0334-4.9858e-03j, -0.0364-3.1883e-03j,  0.0435+1.5472e-03j,
        -0.0597-3.7553e-03j, -0.0702-6.4562e-03j, -0.0790-7.1585e-03j,
        -0.0766-4.9782e-03j, -0.0469-7.3948e-03j, -0.0413-8.8211e-03j,
        -0.0491+3.4423e-04j, -0.0716+4.9138e-04j, -0.0813-8.3465e-03j,
        -0.0760-5.6057e-03j, -0.0726-9.6498e-03j, -0.0648-5.4878e-03j,
        -0.0561-6.3071e-03j, -0.0675-4.1942e-03j, -0.0774+6.4895e-04j,
        -0.0902+5.2829e-04j, -0.0955+6.5805e-04j, -0.0836-6.4208e-03j,
        -0.0721-6.8851e-03j, -0.0594-6.3919e-03j, -0.0597-4.6359e-03j,
        -0.0758-3.2850e-03j, -0.0918-8.0501e-03j, -0.1010-8.2043e-03j,
        -0.0991-2.4382e-03j, -0.0980-2.6585e-03j, -0.0798-4.8036e-03j,
         0.0605+7.7147e-03j, -0.0442-2.5516e-03j, -0.0494-2.7256e-03j,
      

In [ ]:
mg.op_list[i].hopping.M_plus_list[-1].flatten()[:100]=1

In [ ]:
mg.op_list[i].hopping.M_plus_list[-2].flatten()[:100]

tensor([ 0.0758+7.8482e-03j, -0.0858-5.2586e-04j, -0.0819+3.9419e-03j,
         0.0693-6.2976e-03j, -0.0522+6.5747e-03j, -0.0506+3.6383e-03j,
        -0.0452-1.4303e-03j, -0.0498-8.1110e-03j, -0.0741-4.8843e-03j,
        -0.0809-3.1177e-03j, -0.0728-2.5975e-03j, -0.0543-1.0771e-03j,
        -0.0350-1.7086e-03j, -0.0425-5.2585e-03j, -0.0521-4.6038e-03j,
        -0.0579-4.8661e-03j, -0.0654-7.9097e-04j, -0.0547+2.3404e-03j,
        -0.0476+4.8776e-03j, -0.0355+7.5231e-04j, -0.0313-2.2749e-03j,
        -0.0337-6.7864e-03j, -0.0472-9.0637e-03j, -0.0644-7.9895e-03j,
        -0.0571+3.0191e-03j, -0.0474+6.9585e-03j, -0.0277+4.3732e-03j,
        -0.0202+4.2484e-04j, -0.0268-3.6603e-03j, -0.0295-5.0831e-03j,
        -0.0409-1.8107e-03j,  0.0575+4.1104e-03j, -0.0711+3.7279e-03j,
        -0.0533+5.7580e-03j, -0.0325+3.2503e-03j, -0.0242+3.5668e-03j,
        -0.0289-3.4389e-04j, -0.0380-5.8780e-03j, -0.0520-2.8941e-03j,
         0.0669-4.6456e-04j, -0.0741-1.4754e-03j, -0.0658-1.3458e-03j,
      

In [ ]:
mg.op_list[i].hopping.M_minus_list[-1].flatten()[:100]=1