In [11]:
import torch
import mpi4py.MPI as MPI
from pyqcu.ascend import qcu
lat_n = 8
_qcu = qcu(lat_size=[lat_n, lat_n, lat_n, lat_n], dtype=torch.complex128,
           device=torch.device('cpu'), dslash='wilson', verbose=True)
_qcu.load(file_name='test.ascend-dev56')
_qcu.init()
# _qcu.solve()
# _qcu.save(file_name='test.ascend-dev56')
comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()
print(f"rank,size: {rank,size}")


self.lat_size: [8, 8, 8, 8]
self.grid_size: [1, 1, 1, 1]
self.grid_index: [0, 0, 0, 0]
self.local_lat_size: [8, 8, 8, 8]
Using device: cpu
@My Rank:0/1, Local Rank:0@

Grid Index T: 0, Z: 0, Y: 0, X: 0
Grid Lat T: 8, Z: 8, Y: 8, X: 8
All Dest Shape: (4, 3, 8, 8, 8, 8)
Dest Shape: (4, 3, 8, 8, 8, 8)
Grid Index T: 0, Z: 0, Y: 0, X: 0
Grid Lat T: 8, Z: 8, Y: 8, X: 8
All Dest Shape: (4, 3, 8, 8, 8, 8)
Dest Shape: (4, 3, 8, 8, 8, 8)
Grid Index T: 0, Z: 0, Y: 0, X: 0
Grid Lat T: 8, Z: 8, Y: 8, X: 8
All Dest Shape: (3, 3, 4, 8, 8, 8, 8)
Dest Shape: (3, 3, 4, 8, 8, 8, 8)
Grid Index T: 0, Z: 0, Y: 0, X: 0
Grid Lat T: 8, Z: 8, Y: 8, X: 8
All Dest Shape: (4, 3, 4, 3, 8, 8, 8, 8)
Dest Shape: (4, 3, 4, 3, 8, 8, 8, 8)
self.dof_list:[12, 24, 24, 24, 24]
Building grid list:
  Level 0: 8x8x8x8
  Level 1: 4x4x4x4
  Level 2: 2x2x2x2
self.grid_list:[[8, 8, 8, 8], [4, 4, 4, 4], [2, 2, 2, 2]]
rank,size: (0, 1)


In [12]:
_qcu.matvec(_qcu.x)-_qcu.b

tensor([[[[[[ 2.2330e-01-2.8367e-02j,  4.6258e-01+1.6713e-01j,
              5.1896e-01+1.1841e-01j,  ...,
             -3.6077e-01+1.6415e-02j,  1.2695e-01+1.3634e-01j,
             -7.8000e-02+4.1739e-01j],
            [ 1.1866e-01+4.3567e-02j,  2.4532e-01+2.3330e-01j,
              1.8842e-01+4.6736e-02j,  ...,
              2.6918e-01+2.4333e-01j,  8.6674e-02-1.0093e-01j,
             -1.5604e-01+4.7485e-02j],
            [ 2.9718e-02+9.1081e-02j,  2.8664e-01+1.9905e-01j,
              5.0327e-02+1.5614e-02j,  ...,
              7.8759e-02+1.4029e-01j,  5.4611e-02+1.6617e-01j,
              5.4763e-02+4.3506e-01j],
            ...,
            [-1.0980e-01+1.3741e-02j,  2.6269e-01+7.3386e-02j,
             -7.7160e-02+5.7127e-02j,  ...,
              9.6140e-02+2.1196e-01j,  7.0628e-02+3.4930e-02j,
              6.0544e-02-1.9903e-01j],
            [ 2.2453e-01-2.8026e-01j,  4.0899e-01-2.7189e-01j,
             -4.9007e-02+1.8787e-01j,  ...,
             -1.3971e-01+5.4839e-02j, -2

In [13]:
_x = hdf5_xxx2xxx(device=device, file_name=file_name+'-x.h5')
_b = hdf5_xxx2xxx(device=device, file_name=file_name+'-b.h5')
_U = hdf5_xxx2xxx(device=device, file_name=file_name+'-U.h5')
_clover_term = hdf5_xxx2xxx(
    device=device, file_name=file_name+'-clover_term.h5')

Dest Shape: (4, 3, 8, 8, 8, 8)
Dest Shape: (4, 3, 8, 8, 8, 8)
Dest Shape: (3, 3, 4, 8, 8, 8, 8)
Dest Shape: (4, 3, 4, 3, 8, 8, 8, 8)


In [14]:
_x-_qcu.x

tensor([[[[[[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            ...,
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

           [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            ...,
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

           [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
          

In [15]:
_b-_qcu.b

tensor([[[[[[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            ...,
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

           [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            ...,
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

           [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
            [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
          

In [16]:
_U-_qcu.U

tensor([[[[[[[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             ...,
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

            [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             ...,
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

            [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+

In [17]:
_clover_term-_qcu.clover_term

tensor([[[[[[[[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              ...,
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

             [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              ...,
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

             [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+

In [18]:
_clover_term

tensor([[[[[[[[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              ...,
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

             [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              ...,
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j]],

             [[0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+