In [20]:
import numpy as np
import cupy as cp
from pyqcu.cuda import define
from pyqcu.cuda import io
from pyqcu.cuda import qcu
from pyqcu.cuda.set import params, argv, set_ptrs
print('My rank is ', define.rank)
params[define._LAT_X_] = 4
params[define._LAT_Y_] = 2
params[define._LAT_Z_] = 2
params[define._LAT_T_] = 2
params[define._LAT_XYZT_] = params[define._LAT_X_] * \
    params[define._LAT_Y_]*params[define._LAT_Z_]*params[define._LAT_T_]
params[define._GRID_X_] = 1
params[define._GRID_Y_] = 1
params[define._GRID_Z_] = 1
params[define._GRID_T_] = 1
params[define._PARITY_] = 0
params[define._NODE_RANK_] = define.rank
params[define._NODE_SIZE_] = define.size
params[define._DATA_TYPE_] = define._LAT_C64_
dtype = define.dtype(_data_type_=params[define._DATA_TYPE_])
params[define._VERBOSE_] = 1
print("Parameters:", params)
argv[define._MASS_] = 0.0
print("Arguments:", argv)
#############################
gauge = cp.zeros(shape=[define._LAT_C_, define._LAT_C_, define._LAT_D_, params[define._LAT_T_],
                 params[define._LAT_Z_], params[define._LAT_Y_], params[define._LAT_X_]], dtype=dtype)
gauge = io.xxxtzyx2pxxxtzyx(input_array=gauge)
gauge = io.pccdtzyx2ccdptzyx(gauge=gauge)
print("Gauge Shape:", gauge.shape)

My rank is  0
Parameters: [    4     2     2     2    32     1     1     1     1     0     0     1
     0 10000     3     0     0     4     4     4     8    24     1    42]
Arguments: [0.e+00 1.e-09 1.e-01]
Splited Array Shape: (2, 3, 3, 4, 2, 2, 2, 2)
Gauge Shape: (3, 3, 4, 2, 2, 2, 2, 2)


In [21]:
gauge.shape

(3, 3, 4, 2, 2, 2, 2, 2)

In [22]:

#############################
qcu.applyInitQcu(set_ptrs, params, argv)
qcu.applyGaussGaugeQcu(gauge, set_ptrs, params)
print(gauge)
qcu.applyEndQcu(set_ptrs, params)
#############################



set_ptr:0x55b37cfdc170
long long set_ptr:94229384511856
gridDim.x               :1
blockDim.x              :16
host_params[_LAT_X_]    :2
host_params[_LAT_Y_]    :2
host_params[_LAT_Z_]    :2
host_params[_LAT_T_]    :2
host_params[_LAT_XYZT_] :16
host_params[_GRID_X_]   :1
host_params[_GRID_Y_]   :1
host_params[_GRID_Z_]   :1
host_params[_GRID_T_]   :1
host_params[_PARITY_]   :0
host_params[_NODE_RANK_]:0
host_params[_NODE_SIZE_]:1
host_params[_DAGGER_]   :0
host_params[_MAX_ITER_] :10000
host_params[_DATA_TYPE_]:3
host_params[_SET_INDEX_]:0
host_params[_SET_PLAN_] :0
host_params[_MG_X_]     :4
host_params[_MG_Y_]     :4
host_params[_MG_Z_]     :4
host_params[_MG_T_]     :8
host_params[_LAT_E_]    :24
host_params[_VERBOSE_]  :1
host_argv[_MASS_]       :0.000000e+00
host_argv[_TOL_]        :1.000000e-09
host_argv[_SIGMA_]      :1.000000e-01
lat_2dim[_XY_]          :4
lat_2dim[_XZ_]          :4
lat_2dim[_XT_]          :4
lat_2dim[_YZ_]          :4
lat_2dim[_YT_]          :4
lat_2dim[_ZT_

In [23]:
params[define._LAT_XYZT_]

np.int32(32)

In [24]:
gauge[:,:,:,0,...]

array([[[[[[[     0.    +0.j,      0.    +0.j],
            [     0.    +0.j,      0.    +0.j]],

           [[     0.    +0.j,      0.    +0.j],
            [     0.    +0.j,      0.    +0.j]]],


          [[[     0.    +0.j,      0.    +0.j],
            [     0.    +0.j,      0.    +0.j]],

           [[     0.    +0.j,      0.    +0.j],
            [     0.    +0.j,      0.    +0.j]]]],



         [[[[     0.    +0.j,      0.    +0.j],
            [     0.    +0.j,      0.    +0.j]],

           [[     0.    +0.j,      0.    +0.j],
            [     0.    +0.j,      0.    +0.j]]],


          [[[     0.    +0.j,      0.    +0.j],
            [     0.    +0.j,      0.    +0.j]],

           [[     0.    +0.j,      0.    +0.j],
            [     0.    +0.j,      0.    +0.j]]]],



         [[[[     0.+11111.j,      0.+11111.j],
            [     0.+11111.j,      0.+11111.j]],

           [[     0.+11111.j,      0.+11111.j],
            [     0.+11111.j,      0.+11111.j]]],


      

In [39]:
gauge[:,:,:,1,...]

array([[[[[[[ 44444.+22222.j,  44444.+22222.j],
            [ 44444.+22222.j,  44444.+22222.j]],

           [[ 44444.+22222.j,  44444.+22222.j],
            [ 44444.+22222.j,  44444.+22222.j]]],


          [[[ 44444.+22222.j,  44444.+22222.j],
            [ 44444.+22222.j,  44444.+22222.j]],

           [[ 44444.+22222.j,  44444.+22222.j],
            [ 44444.+22222.j,  44444.+22222.j]]]],



         [[[[-44444.-22222.j, -44444.-22222.j],
            [-44444.-22222.j, -44444.-22222.j]],

           [[-44444.-22222.j, -44444.-22222.j],
            [-44444.-22222.j, -44444.-22222.j]]],


          [[[-44444.-22222.j, -44444.-22222.j],
            [-44444.-22222.j, -44444.-22222.j]],

           [[-44444.-22222.j, -44444.-22222.j],
            [-44444.-22222.j, -44444.-22222.j]]]],



         [[[[ 44444.+33333.j,  44444.+33333.j],
            [ 44444.+33333.j,  44444.+33333.j]],

           [[ 44444.+33333.j,  44444.+33333.j],
            [ 44444.+33333.j,  44444.+33333.j]]],


      

In [25]:
gauge.shape

(3, 3, 4, 2, 2, 2, 2, 2)

In [26]:
io.ccdptzyx2pccdtzyx(gauge=gauge)

array([[[[[[[[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]],

            [[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]]],


           [[[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]],

            [[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]]]],



          [[[[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]],

            [[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]]],


           [[[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]],

            [[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]]]],



          [[[[     0.+11111.j,      0.+11111.j],
             [     0.+11111.j,      0.+11111.j]],

            [[     0.+11111.j,      0.+11111.j],
             [     0.+11111.j,      0.+

In [27]:
_gauge=io.ccdptzyx2pccdtzyx(gauge=gauge)
_gauge

array([[[[[[[[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]],

            [[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]]],


           [[[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]],

            [[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]]]],



          [[[[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]],

            [[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]]],


           [[[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]],

            [[     0.    +0.j,      0.    +0.j],
             [     0.    +0.j,      0.    +0.j]]]],



          [[[[     0.+11111.j,      0.+11111.j],
             [     0.+11111.j,      0.+11111.j]],

            [[     0.+11111.j,      0.+11111.j],
             [     0.+11111.j,      0.+

In [28]:

_gauge = io.pxxxtzyx2xxxtzyx(input_array=_gauge)
index = 0
_U = _gauge[:, :, index, index, index, index, index]

Restored Array Shape: (3, 3, 4, 2, 2, 2, 4)


In [29]:
((8 * 4 + 3) * 2+ 1) * 128

9088

In [30]:
params[define._LAT_XYZT_]*36

np.int32(1152)

In [31]:
cp.sum(gauge)

array(0.+0.j, dtype=complex64)

In [32]:
_gauge.shape

(3, 3, 4, 2, 2, 2, 4)

In [33]:
_U

array([[    0.    +0.j,     0.+22222.j, 11111.    +0.j],
       [11111.+22222.j, 22222.    +0.j, 22222.+22222.j],
       [33333.    +0.j, 33333.+22222.j, 44444.    +0.j]], dtype=complex64)

In [34]:
params[define._LAT_XYZT_]

np.int32(32)

In [35]:
640-128

512

In [36]:
_U.shape

(3, 3)

In [37]:
from pyqcu.cuda.gauge import test_su3
test_su3(_U)

U.conj().T @ U =
 [[1.7283604e+09+2.0000000e+00j 1.3579976e+09+2.4690864e+08j
  2.2221778e+09-2.4690864e+08j]
 [1.3579976e+09-2.4690864e+08j 2.5925407e+09+2.6000000e+01j
  1.9752691e+09-7.4072595e+08j]
 [2.2221778e+09+2.4690864e+08j 1.9752691e+09+7.4072595e+08j
  3.0863580e+09+4.0000000e+00j]]
 Is SU(3) a member : False
U[6] = (33333+0j), c6 = (-740725888-493817280j)
U[7] = (33333+22222j), c7 = (123454320-246908640j)
U[8] = (44444+0j), c8 = (493817280+246908640j)
 Satisfy three-row complex conjugation properties : False


In [38]:
from cupyx.scipy.linalg import expm
A = cp.eye(3)
expm(a=A)

array([[2.71828183, 0.        , 0.        ],
       [0.        , 2.71828183, 0.        ],
       [0.        , 0.        , 2.71828183]])