In [41]:
import torch
from pyqcu import tools, dslash, lattice
from pyqcu.cuda import qcu, define
from pyqcu.cuda.define import params, argv, set_ptrs
params[define._LAT_X_] = 8
params[define._LAT_Y_] = 8
params[define._LAT_Z_] = 8
params[define._LAT_T_] = 8
params[define._LAT_XYZT_] = params[define._LAT_X_] * \
    params[define._LAT_Y_]*params[define._LAT_Z_]*params[define._LAT_T_]
params[define._GRID_X_], params[define._GRID_Y_], params[define._GRID_Z_], params[
    define._GRID_T_] = tools.give_grid_size()
params[define._PARITY_] = 0
params[define._NODE_RANK_] = define.rank
params[define._NODE_SIZE_] = define.size
params[define._DAGGER_] = 0
params[define._MAX_ITER_] = 1000
params[define._DATA_TYPE_] = define._LAT_C128_
params[define._SET_INDEX_] = 0
params[define._SET_PLAN_] = 1
params[define._MG_X_] = 1
params[define._MG_Y_] = 1
params[define._MG_Z_] = 1
params[define._MG_T_] = 1
params[define._LAT_E_] = 24
params[define._VERBOSE_] = 1
params[define._SEED_] = 42
argv = argv.to(dtype=define.dtype(params[define._DATA_TYPE_]).to_real())
argv[define._MASS_] = 0.05
argv[define._ATOL_] = 1e-9
argv[define._SIGMA_] = 0.1
#############################
print(params)
print(argv)
print(set_ptrs)

tensor([   8,    8,    8,    8, 4096,    1,    1,    1,    1,    0,    0,    1,
           0, 1000,    3,    0,    1,    1,    1,    1,    1,   24,    1,   42],
       dtype=torch.int32)
tensor([5.0000e-02, 1.0000e-09, 1.0000e-01], dtype=torch.float64)
tensor([94224177216624, 94224177230112, 94224177287536, 94224161148464,
        94224177223920,              0,              0,              0,
                     0,              0])


In [42]:
gauge_eo = torch.zeros(size=[3, 3, 4, 2]+[params[define._LAT_X_], params[define._LAT_Y_], params[define._LAT_Z_],
                       params[define._LAT_T_]//define._LAT_P_]).to(dtype=define.dtype(params[define._DATA_TYPE_]), device=torch.device('cuda'))
fermion_in_eo = torch.rand(size=[2, 4, 3]+[params[define._LAT_X_], params[define._LAT_Y_], params[define._LAT_Z_],
                           params[define._LAT_T_]//define._LAT_P_]).to(dtype=define.dtype(params[define._DATA_TYPE_]), device=torch.device('cuda'))
fermion_out_eo = torch.zeros(size=[2, 4, 3]+[params[define._LAT_X_], params[define._LAT_Y_], params[define._LAT_Z_],
                             params[define._LAT_T_]//define._LAT_P_]).to(dtype=define.dtype(params[define._DATA_TYPE_]), device=torch.device('cuda'))

In [43]:
params[define._VERBOSE_] = 1
params[define._SET_INDEX_] = 0
params[define._SET_PLAN_] = 0
params[define._PARITY_] = 0
qcu.applyInitQcu(set_ptrs, params, argv)
qcu.applyGaussGaugeQcu(gauge_eo, set_ptrs, params)

print(set_ptrs)

set_ptr:0x55b2469c3d40
long long set_ptr:94224177184064
gridDim.x               :128
blockDim.x              :16
host_params[_LAT_X_]    :4
host_params[_LAT_Y_]    :8
host_params[_LAT_Z_]    :8
host_params[_LAT_T_]    :8
host_params[_LAT_XYZT_] :2048
host_params[_GRID_X_]   :1
host_params[_GRID_Y_]   :1
host_params[_GRID_Z_]   :1
host_params[_GRID_T_]   :1
host_params[_PARITY_]   :0
host_params[_NODE_RANK_]:0
host_params[_NODE_SIZE_]:1
host_params[_DAGGER_]   :0
host_params[_MAX_ITER_] :1000
host_params[_DATA_TYPE_]:3
host_params[_SET_INDEX_]:0
host_params[_SET_PLAN_] :0
host_params[_MG_X_]     :1
host_params[_MG_Y_]     :1
host_params[_MG_Z_]     :1
host_params[_MG_T_]     :1
host_params[_LAT_E_]    :24
host_params[_VERBOSE_]  :1
host_argv[_MASS_]       :5.000000e-02
host_argv[_ATOL_]        :1.000000e-09
host_argv[_SIGMA_]      :1.000000e-01
lat_2dim[_XY_]          :32
lat_2dim[_XZ_]          :32
lat_2dim[_XT_]          :32
lat_2dim[_YZ_]          :64
lat_2dim[_YT_]          :64
lat_

In [44]:
gauge_eo.flatten()[:100]

tensor([0.9921+0.0658j, 0.9954+0.0620j, 0.9948+0.0359j, 0.9951+0.0650j,
        0.9898+0.0861j, 0.9932+0.0583j, 0.9906+0.0318j, 0.9875+0.1097j,
        0.9881+0.0185j, 0.9911+0.0435j, 0.9910+0.0637j, 0.9921+0.0293j,
        0.9817+0.1442j, 0.9886+0.0655j, 0.9906+0.1063j, 0.9908+0.0902j,
        0.9829+0.1018j, 0.9890+0.0490j, 0.9889+0.0887j, 0.9913+0.1011j,
        0.9959+0.0369j, 0.9921+0.0885j, 0.9840+0.0931j, 0.9873+0.0615j,
        0.9900+0.0883j, 0.9982+0.0179j, 0.9903+0.0812j, 0.9894+0.0139j,
        0.9876+0.1277j, 0.9881+0.0856j, 0.9869+0.0720j, 0.9856+0.1037j,
        0.9943+0.0222j, 0.9958+0.0577j, 0.9855+0.1014j, 0.9900+0.0287j,
        0.9943+0.0030j, 0.9934+0.0220j, 0.9898+0.1086j, 0.9902+0.0936j,
        0.9861+0.1111j, 0.9946+0.0176j, 0.9832+0.0966j, 0.9874+0.0644j,
        0.9953+0.0151j, 0.9893+0.0980j, 0.9952+0.0138j, 0.9907+0.0897j,
        0.9899+0.0879j, 0.9919+0.0978j, 0.9902+0.1299j, 0.9961+0.0467j,
        0.9883+0.0890j, 0.9928+0.0287j, 0.9909+0.0747j, 0.9982+0

In [45]:
lattice.check_su3(U=gauge_eo)

PYQCU::TESTING::LATTICE:
 [check_su3] Total matrices checked: 16384
PYQCU::TESTING::LATTICE:
 Unitary check   : True
PYQCU::TESTING::LATTICE:
 Determinant=1   : True
PYQCU::TESTING::LATTICE:
 Minor identities: True


True

In [46]:
params[define._VERBOSE_] = 1
params[define._SET_INDEX_] += 1
params[define._SET_PLAN_] = 1
params[define._PARITY_] = 0
qcu.applyInitQcu(set_ptrs, params, argv)
qcu.applyWilsonBistabCgQcu(fermion_out_eo, fermion_in_eo, gauge_eo, set_ptrs, params)

print(set_ptrs)

set_ptr:0x55b245a80b30
long long set_ptr:94224161180464
gridDim.x               :128
blockDim.x              :16
host_params[_LAT_X_]    :4
host_params[_LAT_Y_]    :8
host_params[_LAT_Z_]    :8
host_params[_LAT_T_]    :8
host_params[_LAT_XYZT_] :2048
host_params[_GRID_X_]   :1
host_params[_GRID_Y_]   :1
host_params[_GRID_Z_]   :1
host_params[_GRID_T_]   :1
host_params[_PARITY_]   :0
host_params[_NODE_RANK_]:0
host_params[_NODE_SIZE_]:1
host_params[_DAGGER_]   :0
host_params[_MAX_ITER_] :1000
host_params[_DATA_TYPE_]:3
host_params[_SET_INDEX_]:1
host_params[_SET_PLAN_] :1
host_params[_MG_X_]     :1
host_params[_MG_Y_]     :1
host_params[_MG_Z_]     :1
host_params[_MG_T_]     :1
host_params[_LAT_E_]    :24
host_params[_VERBOSE_]  :1
host_argv[_MASS_]       :5.000000e-02
host_argv[_ATOL_]        :1.000000e-09
host_argv[_SIGMA_]      :1.000000e-01
lat_2dim[_XY_]          :32
lat_2dim[_XZ_]          :32
lat_2dim[_XT_]          :32
lat_2dim[_YZ_]          :64
lat_2dim[_YT_]          :64
lat_

In [47]:
fermion_out_eo.flatten()[:100]

tensor([8.5613-4.5668j, 9.1154-4.3281j, 8.7545-5.0929j, 9.2945-4.1382j,
        8.4273-4.4516j, 8.4964-4.3553j, 8.6847-4.7256j, 8.5722-4.2167j,
        8.9019-4.7908j, 9.3310-4.6934j, 8.8573-4.9066j, 9.0080-5.0752j,
        8.2866-4.5431j, 9.6124-4.4958j, 9.0384-4.6197j, 8.7595-4.2629j,
        8.1566-4.6414j, 8.3694-4.6414j, 8.5203-4.6476j, 8.0208-4.6772j,
        8.9370-4.2852j, 8.3329-4.4855j, 8.1961-4.3771j, 8.2994-4.3442j,
        7.9207-4.3580j, 8.5874-4.6268j, 8.6797-4.6827j, 9.4443-4.5530j,
        8.2399-4.6897j, 8.9855-3.7864j, 8.3957-4.5750j, 9.2464-4.3929j,
        8.2131-4.5621j, 9.0853-4.4919j, 8.8024-4.8371j, 8.6103-4.3804j,
        8.9351-4.9623j, 8.8466-4.4462j, 8.7144-4.5538j, 9.4996-4.1448j,
        8.9932-4.9523j, 9.2207-4.7338j, 8.8771-4.8805j, 8.7421-4.4792j,
        9.2051-4.6857j, 9.0546-4.3175j, 8.8453-4.4857j, 9.0104-4.4750j,
        8.5441-4.7991j, 9.1285-4.5295j, 8.1941-4.2738j, 8.1175-4.4561j,
        8.5034-4.7055j, 8.1410-5.2584j, 8.7547-4.9517j, 9.3097-4

In [48]:
qcu_dest = tools.psctzyx2scxyzt(psctzyx=fermion_out_eo)
qcu_U = tools.ccdptzyx2ccdxyzt(ccdptzyx=gauge_eo)
qcu_src = tools.psctzyx2scxyzt(psctzyx=fermion_in_eo)
refer_src = dslash.give_wilson(
    src=qcu_dest, U=qcu_U, kappa=1 / (2 * argv[define._MASS_] + 8), with_I=True)

In [49]:
qcu_src.flatten()[:100]

tensor([0.5247+0.j, 0.2053+0.j, 0.3271+0.j, 0.3146+0.j, 0.4308+0.j, 0.6008+0.j, 0.7596+0.j,
        0.7795+0.j, 0.6473+0.j, 0.5150+0.j, 0.7352+0.j, 0.1948+0.j, 0.1655+0.j, 0.4484+0.j,
        0.0120+0.j, 0.0529+0.j, 0.6841+0.j, 0.4906+0.j, 0.8252+0.j, 0.3736+0.j, 0.9438+0.j,
        0.0825+0.j, 0.4326+0.j, 0.6211+0.j, 0.5039+0.j, 0.3955+0.j, 0.3287+0.j, 0.4938+0.j,
        0.4080+0.j, 0.5325+0.j, 0.9383+0.j, 0.0328+0.j, 0.6950+0.j, 0.5332+0.j, 0.8276+0.j,
        0.8450+0.j, 0.8641+0.j, 0.4083+0.j, 0.4919+0.j, 0.6919+0.j, 0.6361+0.j, 0.6462+0.j,
        0.9989+0.j, 0.4424+0.j, 0.5022+0.j, 0.1526+0.j, 0.2188+0.j, 0.4008+0.j, 0.8194+0.j,
        0.3169+0.j, 0.5145+0.j, 0.1332+0.j, 0.3250+0.j, 0.9554+0.j, 0.0822+0.j, 0.4483+0.j,
        0.1456+0.j, 0.5937+0.j, 0.9338+0.j, 0.8162+0.j, 0.0671+0.j, 0.1006+0.j, 0.0167+0.j,
        0.8079+0.j, 0.1365+0.j, 0.9549+0.j, 0.3793+0.j, 0.1848+0.j, 0.0637+0.j, 0.0216+0.j,
        0.7622+0.j, 0.0318+0.j, 0.9180+0.j, 0.6072+0.j, 0.0642+0.j, 0.9137+0.j, 

In [50]:
refer_src.flatten()[:100]

tensor([0.5247-2.2204e-16j, 0.2053-1.2899e-07j, 0.3271-1.9984e-15j,
        0.3146-1.6298e-07j, 0.4308-6.6613e-16j, 0.6008-2.0938e-07j,
        0.7596-9.9920e-16j, 0.7795-1.5737e-07j, 0.6473-1.3501e-07j,
        0.5150+7.7716e-16j, 0.7352-1.3283e-07j, 0.1948+2.2204e-16j,
        0.1655-1.9680e-07j, 0.4484+3.3307e-16j, 0.0120-1.9665e-07j,
        0.0529+0.0000e+00j, 0.6841+1.1102e-15j, 0.4906-1.6051e-07j,
        0.8252-2.2204e-16j, 0.3736-1.4759e-07j, 0.9438-4.4409e-16j,
        0.0825-1.7362e-07j, 0.4326-2.2204e-16j, 0.6211-1.4599e-07j,
        0.5039-1.3558e-07j, 0.3955+0.0000e+00j, 0.3287-1.6373e-07j,
        0.4938-9.9920e-16j, 0.4080-1.5467e-07j, 0.5325-3.3307e-16j,
        0.9383-1.5341e-07j, 0.0328-5.5511e-16j, 0.6950-4.4409e-16j,
        0.5332-1.3259e-07j, 0.8276+4.4409e-16j, 0.8450-1.4696e-07j,
        0.8641+0.0000e+00j, 0.4083-1.7233e-07j, 0.4919-8.8818e-16j,
        0.6919-1.5892e-07j, 0.6361-1.3994e-07j, 0.6462-1.3323e-15j,
        0.9989-1.0796e-07j, 0.4424+6.6613e-16j, 

In [51]:
print(tools.norm(refer_src-qcu_src)/tools.norm(qcu_src))

2.235248897479613e-07


In [52]:
clover_ee = torch.zeros(size=[4, 3, 4, 3]+[params[define._LAT_X_], params[define._LAT_Y_], params[define._LAT_Z_],
                       params[define._LAT_T_]//define._LAT_P_]).to(dtype=define.dtype(params[define._DATA_TYPE_]), device=torch.device('cuda'))
clover_ee_inv = torch.zeros(size=[4, 3, 4, 3]+[params[define._LAT_X_], params[define._LAT_Y_], params[define._LAT_Z_],
                       params[define._LAT_T_]//define._LAT_P_]).to(dtype=define.dtype(params[define._DATA_TYPE_]), device=torch.device('cuda'))
clover_oo = torch.zeros(size=[4, 3, 4, 3]+[params[define._LAT_X_], params[define._LAT_Y_], params[define._LAT_Z_],
                       params[define._LAT_T_]//define._LAT_P_]).to(dtype=define.dtype(params[define._DATA_TYPE_]), device=torch.device('cuda'))
clover_oo_inv = torch.zeros(size=[4, 3, 4, 3]+[params[define._LAT_X_], params[define._LAT_Y_], params[define._LAT_Z_],
                       params[define._LAT_T_]//define._LAT_P_]).to(dtype=define.dtype(params[define._DATA_TYPE_]), device=torch.device('cuda'))

In [53]:
params[define._VERBOSE_] = 1
params[define._SET_INDEX_] += 1
params[define._SET_PLAN_] = 2
params[define._PARITY_] = 0
qcu.applyInitQcu(set_ptrs, params, argv)
qcu.applyCloversQcu(clover_ee, clover_ee_inv, gauge_eo, set_ptrs, params)

print(set_ptrs)

set_ptr:0x55b2469e2c10
long long set_ptr:94224177310736
gridDim.x               :128
blockDim.x              :16
host_params[_LAT_X_]    :4
host_params[_LAT_Y_]    :8
host_params[_LAT_Z_]    :8
host_params[_LAT_T_]    :8
host_params[_LAT_XYZT_] :2048
host_params[_GRID_X_]   :1
host_params[_GRID_Y_]   :1
host_params[_GRID_Z_]   :1
host_params[_GRID_T_]   :1
host_params[_PARITY_]   :0
host_params[_NODE_RANK_]:0
host_params[_NODE_SIZE_]:1
host_params[_DAGGER_]   :0
host_params[_MAX_ITER_] :1000
host_params[_DATA_TYPE_]:3
host_params[_SET_INDEX_]:2
host_params[_SET_PLAN_] :2
host_params[_MG_X_]     :1
host_params[_MG_Y_]     :1
host_params[_MG_Z_]     :1
host_params[_MG_T_]     :1
host_params[_LAT_E_]    :24
host_params[_VERBOSE_]  :1
host_argv[_MASS_]       :5.000000e-02
host_argv[_ATOL_]        :1.000000e-09
host_argv[_SIGMA_]      :1.000000e-01
lat_2dim[_XY_]          :32
lat_2dim[_XZ_]          :32
lat_2dim[_XT_]          :32
lat_2dim[_YZ_]          :64
lat_2dim[_YT_]          :64
lat_

In [54]:
params[define._VERBOSE_] = 1
params[define._SET_INDEX_] += 1
params[define._SET_PLAN_] = 2
params[define._PARITY_] = 1
qcu.applyInitQcu(set_ptrs, params, argv)
qcu.applyCloversQcu(clover_oo, clover_oo_inv, gauge_eo, set_ptrs, params)

print(set_ptrs)

set_ptr:0x55b2469ce1c0
long long set_ptr:94224177226176
gridDim.x               :128
blockDim.x              :16
host_params[_LAT_X_]    :4
host_params[_LAT_Y_]    :8
host_params[_LAT_Z_]    :8
host_params[_LAT_T_]    :8
host_params[_LAT_XYZT_] :2048
host_params[_GRID_X_]   :1
host_params[_GRID_Y_]   :1
host_params[_GRID_Z_]   :1
host_params[_GRID_T_]   :1
host_params[_PARITY_]   :1
host_params[_NODE_RANK_]:0
host_params[_NODE_SIZE_]:1
host_params[_DAGGER_]   :0
host_params[_MAX_ITER_] :1000
host_params[_DATA_TYPE_]:3
host_params[_SET_INDEX_]:3
host_params[_SET_PLAN_] :2
host_params[_MG_X_]     :1
host_params[_MG_Y_]     :1
host_params[_MG_Z_]     :1
host_params[_MG_T_]     :1
host_params[_LAT_E_]    :24
host_params[_VERBOSE_]  :1
host_argv[_MASS_]       :5.000000e-02
host_argv[_ATOL_]        :1.000000e-09
host_argv[_SIGMA_]      :1.000000e-01
lat_2dim[_XY_]          :32
lat_2dim[_XZ_]          :32
lat_2dim[_XT_]          :32
lat_2dim[_YZ_]          :64
lat_2dim[_YT_]          :64
lat_

In [55]:
fermion_out_eo = torch.zeros(size=[2, 4, 3]+[params[define._LAT_X_], params[define._LAT_Y_], params[define._LAT_Z_],
                             params[define._LAT_T_]//define._LAT_P_]).to(dtype=define.dtype(params[define._DATA_TYPE_]), device=torch.device('cuda'))

In [56]:
params[define._VERBOSE_] = 1
params[define._SET_INDEX_] += 1
params[define._SET_PLAN_] = 1
params[define._PARITY_] = 0
qcu.applyInitQcu(set_ptrs, params, argv)
qcu.applyCloverBistabCgQcu(fermion_out_eo, fermion_in_eo, gauge_eo,
                           clover_ee, clover_oo, clover_ee_inv, clover_oo_inv,  set_ptrs, params)

print(set_ptrs)

set_ptr:0x55b246bde220
long long set_ptr:94224179388960
gridDim.x               :128
blockDim.x              :16
host_params[_LAT_X_]    :4
host_params[_LAT_Y_]    :8
host_params[_LAT_Z_]    :8
host_params[_LAT_T_]    :8
host_params[_LAT_XYZT_] :2048
host_params[_GRID_X_]   :1
host_params[_GRID_Y_]   :1
host_params[_GRID_Z_]   :1
host_params[_GRID_T_]   :1
host_params[_PARITY_]   :0
host_params[_NODE_RANK_]:0
host_params[_NODE_SIZE_]:1
host_params[_DAGGER_]   :0
host_params[_MAX_ITER_] :1000
host_params[_DATA_TYPE_]:3
host_params[_SET_INDEX_]:4
host_params[_SET_PLAN_] :1
host_params[_MG_X_]     :1
host_params[_MG_Y_]     :1
host_params[_MG_Z_]     :1
host_params[_MG_T_]     :1
host_params[_LAT_E_]    :24
host_params[_VERBOSE_]  :1
host_argv[_MASS_]       :5.000000e-02
host_argv[_ATOL_]        :1.000000e-09
host_argv[_SIGMA_]      :1.000000e-01
lat_2dim[_XY_]          :32
lat_2dim[_XZ_]          :32
lat_2dim[_XT_]          :32
lat_2dim[_YZ_]          :64
lat_2dim[_YT_]          :64
lat_

In [57]:
qcu_dest = tools.psctzyx2scxyzt(psctzyx=fermion_out_eo)
qcu_U = tools.ccdptzyx2ccdxyzt(ccdptzyx=gauge_eo)
qcu_src = tools.psctzyx2scxyzt(psctzyx=fermion_in_eo)
refer_clover_term = dslash.make_clover(
    U=qcu_U, kappa=1 / (2 * argv[define._MASS_] + 8))
refer_src = dslash.give_wilson(
    src=qcu_dest, U=qcu_U, kappa=1 / (2 * argv[define._MASS_] + 8), with_I=True)+dslash.give_clover(src=qcu_dest, clover_term=refer_clover_term)

In [58]:
qcu_src.flatten()[:100]

tensor([0.5247+0.j, 0.2053+0.j, 0.3271+0.j, 0.3146+0.j, 0.4308+0.j, 0.6008+0.j, 0.7596+0.j,
        0.7795+0.j, 0.6473+0.j, 0.5150+0.j, 0.7352+0.j, 0.1948+0.j, 0.1655+0.j, 0.4484+0.j,
        0.0120+0.j, 0.0529+0.j, 0.6841+0.j, 0.4906+0.j, 0.8252+0.j, 0.3736+0.j, 0.9438+0.j,
        0.0825+0.j, 0.4326+0.j, 0.6211+0.j, 0.5039+0.j, 0.3955+0.j, 0.3287+0.j, 0.4938+0.j,
        0.4080+0.j, 0.5325+0.j, 0.9383+0.j, 0.0328+0.j, 0.6950+0.j, 0.5332+0.j, 0.8276+0.j,
        0.8450+0.j, 0.8641+0.j, 0.4083+0.j, 0.4919+0.j, 0.6919+0.j, 0.6361+0.j, 0.6462+0.j,
        0.9989+0.j, 0.4424+0.j, 0.5022+0.j, 0.1526+0.j, 0.2188+0.j, 0.4008+0.j, 0.8194+0.j,
        0.3169+0.j, 0.5145+0.j, 0.1332+0.j, 0.3250+0.j, 0.9554+0.j, 0.0822+0.j, 0.4483+0.j,
        0.1456+0.j, 0.5937+0.j, 0.9338+0.j, 0.8162+0.j, 0.0671+0.j, 0.1006+0.j, 0.0167+0.j,
        0.8079+0.j, 0.1365+0.j, 0.9549+0.j, 0.3793+0.j, 0.1848+0.j, 0.0637+0.j, 0.0216+0.j,
        0.7622+0.j, 0.0318+0.j, 0.9180+0.j, 0.6072+0.j, 0.0642+0.j, 0.9137+0.j, 

In [59]:
refer_src.flatten()[:100]

tensor([0.5247+2.0817e-17j, 0.2053+1.2070e-07j, 0.3271-6.9389e-16j,
        0.3146+8.3555e-08j, 0.4308+1.6306e-16j, 0.6008+1.7159e-07j,
        0.7596+8.8124e-16j, 0.7795+8.8405e-08j, 0.6473+1.0676e-07j,
        0.5150-7.2164e-16j, 0.7352+8.4699e-08j, 0.1948+5.2736e-16j,
        0.1655+1.4184e-07j, 0.4484-2.7756e-17j, 0.0120+1.1225e-07j,
        0.0529+1.9568e-15j, 0.6841+8.1185e-16j, 0.4906+7.9777e-08j,
        0.8252-4.9266e-16j, 0.3736+1.2124e-07j, 0.9438+1.8041e-16j,
        0.0825+8.6970e-08j, 0.4326-2.8727e-15j, 0.6211+1.2097e-07j,
        0.5039+1.0745e-07j, 0.3955+3.2960e-16j, 0.3287+1.0760e-07j,
        0.4938+1.2074e-15j, 0.4080+7.0744e-08j, 0.5325-1.6653e-15j,
        0.9383+1.1464e-07j, 0.0328+5.4123e-16j, 0.6950-6.2450e-16j,
        0.5332+1.4079e-07j, 0.8276+4.7878e-16j, 0.8450+6.4433e-08j,
        0.8641+3.6082e-16j, 0.4083+1.0727e-07j, 0.4919+1.1102e-16j,
        0.6919+1.1614e-07j, 0.6361+1.4784e-07j, 0.6462+9.9920e-16j,
        0.9989+7.2805e-08j, 0.4424-2.5327e-16j, 

In [60]:
print(tools.norm(refer_src-qcu_src)/tools.norm(qcu_src))

1.8189253083548203e-07
