In [5]:
import torch
from pyqcu import tools, dslash, solver
from pyqcu.cuda import qcu, define
from pyqcu.cuda.define import params, argv, set_ptrs
params[define._LAT_X_] = 8
params[define._LAT_Y_] = 8
params[define._LAT_Z_] = 8
params[define._LAT_T_] = 8
params[define._LAT_XYZT_] = params[define._LAT_X_] * \
    params[define._LAT_Y_]*params[define._LAT_Z_]*params[define._LAT_T_]
params[define._GRID_X_], params[define._GRID_Y_], params[define._GRID_Z_], params[
    define._GRID_T_] = tools.give_grid_size()
params[define._PARITY_] = 0
params[define._NODE_RANK_] = define.rank
params[define._NODE_SIZE_] = define.size
params[define._DAGGER_] = 0
params[define._MAX_ITER_] = 1000
params[define._DATA_TYPE_] = define._LAT_C128_
params[define._SET_INDEX_] = 0
params[define._SET_PLAN_] = 1
params[define._MG_X_] = 1
params[define._MG_Y_] = 1
params[define._MG_Z_] = 1
params[define._MG_T_] = 1
params[define._LAT_E_] = 24
params[define._VERBOSE_] = 1
params[define._SEED_] = 42
argv = argv.to(dtype=define.dtype(params[define._DATA_TYPE_]).to_real())
argv[define._MASS_] = 0.05
argv[define._TOL_] = 1e-12
argv[define._SIGMA_] = 0.1
#############################
print(params)
print(argv)
print(set_ptrs)

tensor([   8,    8,    8,    8, 4096,    1,    1,    1,    1,    0,    0,    1,
           0, 1000,    3,    0,    1,    1,    1,    1,    1,   24,    1,   42],
       dtype=torch.int32)
tensor([5.0000e-02, 1.0000e-12, 1.0000e-01], dtype=torch.float64)
tensor([94239436543808,              0,              0,              0,
                     0,              0,              0,              0,
                     0,              0])


In [2]:
gauge_eo = torch.zeros(size=[3,3,4,2]+[params[define._LAT_X_],params[define._LAT_Y_],params[define._LAT_Z_],params[define._LAT_T_]]).to(dtype=define.dtype(params[define._DATA_TYPE_]),device=torch.device('cuda'))
fermion_in_eo = torch.rand(size=[2,4,3]+[params[define._LAT_X_],params[define._LAT_Y_],params[define._LAT_Z_],params[define._LAT_T_]]).to(dtype=define.dtype(params[define._DATA_TYPE_]),device=torch.device('cuda'))
fermion_out_eo = torch.zeros(size=[2,4,3]+[params[define._LAT_X_],params[define._LAT_Y_],params[define._LAT_Z_],params[define._LAT_T_]]).to(dtype=define.dtype(params[define._DATA_TYPE_]),device=torch.device('cuda'))

In [3]:
params[define._SET_INDEX_] = 0
params[define._SET_PLAN_] = 1
qcu.applyInitQcu(set_ptrs, params, argv)
qcu.applyGaussGaugeQcu(gauge_eo, set_ptrs, params)
qcu.applyEndQcu(set_ptrs, params)
print(set_ptrs)

set_ptr:0x55b5d4239740
long long set_ptr:94239436543808
gridDim.x               :128
blockDim.x              :16
host_params[_LAT_X_]    :4
host_params[_LAT_Y_]    :8
host_params[_LAT_Z_]    :8
host_params[_LAT_T_]    :8
host_params[_LAT_XYZT_] :2048
host_params[_GRID_X_]   :1
host_params[_GRID_Y_]   :1
host_params[_GRID_Z_]   :1
host_params[_GRID_T_]   :1
host_params[_PARITY_]   :0
host_params[_NODE_RANK_]:0
host_params[_NODE_SIZE_]:1
host_params[_DAGGER_]   :0
host_params[_MAX_ITER_] :1000
host_params[_DATA_TYPE_]:3
host_params[_SET_INDEX_]:0
host_params[_SET_PLAN_] :1
host_params[_MG_X_]     :1
host_params[_MG_Y_]     :1
host_params[_MG_Z_]     :1
host_params[_MG_T_]     :1
host_params[_LAT_E_]    :24
host_params[_VERBOSE_]  :1
host_argv[_MASS_]       :5.000000e-02
host_argv[_TOL_]        :1.000000e-12
host_argv[_SIGMA_]      :1.000000e-01
lat_2dim[_XY_]          :32
lat_2dim[_XZ_]          :32
lat_2dim[_XT_]          :32
lat_2dim[_YZ_]          :64
lat_2dim[_YT_]          :64
lat_2

In [6]:
gauge_eo.flatten()[:100]

tensor([0.9921+0.0658j, 0.9954+0.0620j, 0.9948+0.0359j, 0.9951+0.0650j,
        0.9898+0.0861j, 0.9932+0.0583j, 0.9906+0.0318j, 0.9875+0.1097j,
        0.9881+0.0185j, 0.9911+0.0435j, 0.9910+0.0637j, 0.9921+0.0293j,
        0.9817+0.1442j, 0.9886+0.0655j, 0.9906+0.1063j, 0.9908+0.0902j,
        0.9829+0.1018j, 0.9890+0.0490j, 0.9889+0.0887j, 0.9913+0.1011j,
        0.9959+0.0369j, 0.9921+0.0885j, 0.9840+0.0931j, 0.9873+0.0615j,
        0.9900+0.0883j, 0.9982+0.0179j, 0.9903+0.0812j, 0.9894+0.0139j,
        0.9876+0.1277j, 0.9881+0.0856j, 0.9869+0.0720j, 0.9856+0.1037j,
        0.9943+0.0222j, 0.9958+0.0577j, 0.9855+0.1014j, 0.9900+0.0287j,
        0.9943+0.0030j, 0.9934+0.0220j, 0.9898+0.1086j, 0.9902+0.0936j,
        0.9861+0.1111j, 0.9946+0.0176j, 0.9832+0.0966j, 0.9874+0.0644j,
        0.9953+0.0151j, 0.9893+0.0980j, 0.9952+0.0138j, 0.9907+0.0897j,
        0.9899+0.0879j, 0.9919+0.0978j, 0.9902+0.1299j, 0.9961+0.0467j,
        0.9883+0.0890j, 0.9928+0.0287j, 0.9909+0.0747j, 0.9982+0

In [ ]:
params[define._VERBOSE_] = 1
params[define._SET_INDEX_] += 1
params[define._SET_PLAN_] = 1
#############################
define.applyInitQcu(set_ptrs, params, argv)
define.applyWilsonBistabCgQcu(
    wilson_fermion_out, fermion_in, gauge, set_ptrs, params)
define.applyEndQcu(set_ptrs, params)
#############################
clover_ee = io.give_none_clover(params, save=False)
clover_ee_inv = cp.zeros_like(clover_ee)
clover_oo = cp.zeros_like(clover_ee)
clover_oo_inv = cp.zeros_like(clover_ee)
#############################
params[define._VERBOSE_] = 1
params[define._SET_INDEX_] += 1
params[define._SET_PLAN_] = 2
params[define._PARITY_] = 0
#############################
define.applyInitQcu(set_ptrs, params, argv)
define.applyCloversQcu(clover_ee, clover_ee_inv, gauge, set_ptrs, params)
define.applyEndQcu(set_ptrs, params)
#############################
params[define._VERBOSE_] = 1
params[define._SET_INDEX_] += 1
params[define._SET_PLAN_] = 2
params[define._PARITY_] = 1
#############################
define.applyInitQcu(set_ptrs, params, argv)
define.applyCloversQcu(clover_oo, clover_oo_inv, gauge, set_ptrs, params)
define.applyEndQcu(set_ptrs, params)
#############################
params[define._VERBOSE_] = 1
params[define._SET_INDEX_] += 1
params[define._SET_PLAN_] = 1
#############################
define.applyInitQcu(set_ptrs, params, argv)
define.applyCloverBistabCgQcu(clover_fermion_out, fermion_in,
                           gauge, clover_ee, clover_oo, clover_ee_inv, clover_oo_inv,  set_ptrs, params)
define.applyEndQcu(set_ptrs, params)
#############################
if os.path.exists("_gauge-test8.h5") and os.path.exists("_fermion_in-test8.h5") and os.path.exists("_wilson_fermion_out-test8.h5") and os.path.exists("_clover_fermion_out-test8.h5"):
    io.grid_xxxtzyx2hdf5_xxxtzyx(
        wilson_fermion_out, params, "_wilson_fermion_out-test8.h5")
    io.grid_xxxtzyx2hdf5_xxxtzyx(
        clover_fermion_out, params, "_clover_fermion_out-test8.h5")
    print(
        f"@cp.linalg.norm(wilson_fermion_out-_wilson_fermion_out)/cp.linalg.norm(wilson_fermion_out):{cp.linalg.norm(wilson_fermion_out-_wilson_fermion_out)/cp.linalg.norm(wilson_fermion_out)}@")
    print(
        f"@cp.linalg.norm(clover_fermion_out-_clover_fermion_out)/cp.linalg.norm(clover_fermion_out):{cp.linalg.norm(clover_fermion_out-_clover_fermion_out)/cp.linalg.norm(clover_fermion_out)}@")
#############################